services:
  sharepoint-docs-mcp:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env

    # 証明書ファイルを使用する場合のボリュームマウント
    volumes:
      - ./cert:/app/cert:ro

    # ヘルスチェック
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s